apiVersion: v1
kind: Service
metadata:
  name: app-java-basico-service
spec:
  type: LoadBalancer
  selector:
    app: app-java-basico
  ports:
    - protocol: TCP
      port: 80  
      targetPort: 9000